// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/data": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据管理"
                ],
                "summary": "显示当前用户可见的所有数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数,默认为1",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页大小，默认为7",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "当前用户id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "条件筛选: 设备ID",
                        "name": "nodeID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "条件筛选: 物理量",
                        "name": "dataName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "条件筛选: 时间:yy.mm.dd hh:mm:ss - yy.mm.dd hh:mm:ss",
                        "name": "time",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    }
                }
            }
        },
        "/data/download/:id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据管理"
                ],
                "summary": "导出当前用户的所有可见设备的数据",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前用户id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "条件筛选: 设备ID",
                        "name": "nodeID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "条件筛选: 物理量",
                        "name": "dataName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "条件筛选: 时间:yy.mm.dd hh:mm:ss - yy.mm.dd hh:mm:ss",
                        "name": "time",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "下载成功",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户输入用户名和密码登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "用户对象，包括用户名和密码两个属性",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    },
                    "422": {
                        "description": "密码错误",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    },
                    "442": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    },
                    "500": {
                        "description": "系统发放token异常",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/node": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "获取所有设备信息",
                "responses": {
                    "200": {
                        "description": "返回设备列表",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "管理员新建设备",
                "parameters": [
                    {
                        "description": "新设备",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Node"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "442": {
                        "description": "设备已存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/node/:id": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "展示当前用户可见设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前用户的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回设备列表",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "管理员修改设备信息",
                "parameters": [
                    {
                        "description": "新设备",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Node"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "具体修改的设备的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "设备不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "管理员删除设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "具体删除的设备ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    },
                    "400": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/node/setTime": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "设备管理"
                ],
                "summary": "管理员修改设备系统时间",
                "parameters": [
                    {
                        "type": "string",
                        "description": "yy.mm.dd hh:mm:ss",
                        "name": "time",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "442": {
                        "description": "Server无响应",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/phy": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物理量管理"
                ],
                "summary": "展示9种物理量的信息",
                "responses": {
                    "200": {
                        "description": "返回物理量列表",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/phy/:id": {
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "物理量管理"
                ],
                "summary": "管理员修改物理量信息",
                "parameters": [
                    {
                        "description": "物理量信息",
                        "name": "node",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Physical"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "具体修改的物理量的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "物理量不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "用于管理员注册新用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "新用户，传入用户名和密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "442": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取登录用户的信息",
                "responses": {
                    "200": {
                        "description": "返回用户id，头像avatar，用户名name,用户角色role",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "管理员修改用户信息",
                "parameters": [
                    {
                        "description": "新用户的用户名、密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    },
                    {
                        "type": "integer",
                        "description": "具体修改的用户的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "管理员添加用户",
                "parameters": [
                    {
                        "description": "新用户的用户名、密码",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "442": {
                        "description": "用户已存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "管理员修改用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "具体修改的用户的ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponse"
                        }
                    },
                    "400": {
                        "description": "用户不存在",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        },
        "/user/users": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "管理员获取所有用户信息及其设备",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页数，默认为1",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数据个数，默认为5",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回用户列表users，用户个数count",
                        "schema": {
                            "$ref": "#/definitions/controller.SwaggerResponseData"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.SwaggerResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "msg": {
                    "description": "描述",
                    "type": "string"
                }
            }
        },
        "controller.SwaggerResponseData": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "响应码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "msg": {
                    "description": "描述",
                    "type": "string"
                }
            }
        },
        "model.Node": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "nodeName": {
                    "type": "string"
                },
                "state": {
                    "type": "integer"
                }
            }
        },
        "model.Physical": {
            "type": "object",
            "properties": {
                "chinese_name": {
                    "type": "string"
                },
                "conversion": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "meaning": {
                    "type": "string"
                },
                "physicalName": {
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "description": "0:管理员 , 1: 普通用户",
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:9027",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "天气管理系统后端API文档",
	Description:      "API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
